### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/react-vtk-js#15]
Hi, I'm not sure how to reproduce this, but on my Create React App project I get the following webpack warning when I use react-vtk-js, everything seems to work but I get this warning. May you help me understand what's going on please?

```
Failed to compile.

../node_modules/react-vtk-js/dist/esm/node_modules/@kitware/vtk.js/_virtual/commonjsHelpers.js
Critical dependency: the request of a dependency is an expression
```

**Comment by FezVrasta** [comment]
I think the problem is if the project ends up including different versions of vtk.js at the same time, but honestly it's just guess work. I set a `resolutions` field for Yarn to make sure I only use a specific version across the project and the warning went away, but it may be unrelated.

**Comment by jourdain** [comment]
I see, but I'm not sure either. I don't like to use a loose version number as I've been bitten before on that. Do you have another dependency bringing vtk.js?

**Comment by FezVrasta** [comment]
I use vtk.js directly, I could align my own version with the one used by react-vtk-js but we end up quite often needing the most recent version because it includes bugfixes we rely on.

**Comment by jourdain** [comment]
I see then it might be fine to use a more flex version number in the react part.
