### ISSUE TITLE
Text rendering?

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/react-vtk-js#23]
Hi, does this library expose any component that can help me render some text?

**Comment by FezVrasta** [comment]
Thanks, I was hoping for something that would handle for me rotation, world coordinates and such though 🤔 

If I went with your suggestion what should I use to convert the world coordinates to the display ones? If I get the `view` from the `Contexts.ViewContext` context its interactor doesn't seem to have the `computeWorldToDisplay` property.

**Comment by jourdain** [comment]
Maybe now you can explain what that text is for and what you are trying to do. Because that was just a solution among many. Which might not be the best for you. Do you want the text to scale based on the distance from the camera? Do you want the text to always face the camera? Are you looking to do a cube axes?

**Comment by FezVrasta** [comment]
yeah sorry, basically I need to display some text near a geometry (annotation) that the user draws on the canvas. It's just like what you have with the distance widget that VTK provides out of the box.

**Comment by jourdain** [comment]
You probably want to use something with vtkPixelSpaceCallbackMapper like in that [example](https://kitware.github.io/vtk-js/examples/SpheresAndLabels.html)

HTH

**Comment by FezVrasta** [comment]
Thanks, for now I managed to render some text using your initially proposed approach.

```js
  const viewCtx = useContext(Contexts.ViewContext);
  const renderer = viewCtx?.renderer;
  const view = renderer?.getRenderWindow()?.getViews()[0];

  const [displayCoordinates, setDisplayCoordinates] = useState(
    view?.worldToDisplay(point[0], point[1], point[2], renderer) ?? [0, 0]
  );

  useEffect(() => {
    viewCtx?.interactor.onRenderEvent(() =>
      setDisplayCoordinates(view?.worldToDisplay(point[0], point[1], point[2], renderer) ?? [0, 0])
    );
  }, [point, renderer, view, viewCtx?.interactor]);
```

It seems to work very good so I'll stick with it unless problems araise.

I'd love to see a first-party Label component though!

**Comment by jourdain** [comment]
Feel free to make a PR with it and we can see if we want to improve it down the road.

**Comment by FezVrasta** [comment]
@jourdain I realized my code above has a performance issue, the `onRenderEvent` is called for each actor in the view, so the component gets needlessly rerendered a lot when there are a lot of actors.

Could you suggest a more performant way to update the coordinates when the view changes?

**Comment by jourdain** [comment]
You can [throttle](https://github.com/Kitware/vtk-js/blob/master/Sources/macros.js#L1022) your callback to not be more than 30 time per seconds.
