### ISSUE TITLE
Can't pick DataArray + SliceRepresentation

### ISSUE THREAD

**Issue by FezVrasta** [Kitware/react-vtk-js#24]
Hi, I enabled picking for my View (`pickingModes={['click']} onClick={selection => console.log(selection)}`) and it works correctly, but as soon I click on a `SliceRepresentation` linked to a `DataArray` element I get the following error:

![CleanShot 2021-08-01 at 11 20 56@2x](https://user-images.githubusercontent.com/5382443/127765993-85e74c61-6bf3-498c-aa9b-c48d571decd8.jpg)

It looks like that here `prop` is undefined:

https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L514

**Comment by jourdain** [comment]
Can you submit a PR with a fix? I can guide you, but I don't have the time to test and push the fix.

On those 2 lines you should check/guard that you have a `prop`, if not, you should skip or make sure we don't call `get` on it... 
- https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L514
- https://github.com/Kitware/react-vtk-js/blob/master/src/core/View.js#L531

Thanks
