### ISSUE TITLE
No input issue and removeActor issue

### ISSUE THREAD

**Issue by saodem74** [Kitware/react-vtk-js#3]
Hello,

Thanks for your contribution to this library.

I'm developing a Reactjs front-end using this library. I'm facing some issues and need your help.

1. I got 7 errors (**No input!**) when I try to visualize an object with Reader from a given URL. But the object still appears on the window. I'm not sure about what properties are missing? 

```
<div style={{width: '40vw', height: '75vh'}}>
  <View>
    <GeometryRepresentation>
      <Reader
              vtkClass="vtkOBJReader"
              url={"https://kitware.github.io/vtk-js-datasets/data/obj-mtl/star-wars-vader-tie-fighter.obj"}
      />
    </GeometryRepresentation>
  </View>
</div>
```
2. When the component is unmounted, it occurs the following error:

```
TypeError: null is not an object (evaluating 'this.view.renderer.removeActor')
```
Since from my code, I can not touch to .view.renderer.removeActor, how could I fix it?

Thanks in advance.

**Comment by jourdain** [comment]
1) The __"No Input"__ issue is a timing one. Meaning some render() are called before all the data is available (downloading). To some extent, you should not have to worry about these errors.

2) This should be fixed on our end. Maybe you could contribute a test for that issue. Ideally, we should start building test to re-enforce that library.

**Comment by saodem74** [comment]
@jourdain Thanks for your response!
