### ISSUE TITLE
Examples not building

### ISSUE THREAD

**Issue by tamaynard** [Kitware/react-vtk-js#32]
Not sure if this is related to #28, but now when attempting to build the examples in the usage folder a whole bunch of dependency errors pop up. An example:

`Module not found: Error: Can't resolve '@kitware/vtk.js/Rendering/Core/ColorTransferFunction/ColorMaps.js' in 'D:\git\react-vtk-js\dist\esm\core'`

**Comment by jourdain** [comment]
That is indeed possible. Thanks for reporting the issue

**Comment by jourdain** [comment]
It might be fixed now with the latest version. Can you double check?

**Comment by tamaynard** [comment]
Seems like it's working now. Thanks for the quick response!
