### ISSUE TITLE
Access internal objects from callback?

### ISSUE THREAD

**Issue by tamaynard** [Kitware/react-vtk-js#36]
Sorry if this seems like a noob question, but I'm curious whether there's a method to access internal objects from the View class in an event callback? I'd like to set some parameters on the camera object (center of rotation to be specific) in the onMouseDown event without having to hack the View.js source directly...

**Comment by tamaynard** [comment]
If not currently supported perhaps I could submit a PR to support this, if desired?

**Comment by jourdain** [comment]
You should be able to do that by having a ref on the view from the parent component that is providing your callback. No code change is actually required.

**Comment by tamaynard** [comment]
Ok I'll give that a shot. Thanks for the advice!
