### ISSUE TITLE
OBJViewer: Loading obj + mtl

### ISSUE THREAD

**Issue by saodem74** [Kitware/react-vtk-js#4]
Hello,

According to this [page](https://kitware.github.io/vtk-js/examples/OBJViewer.html), vtk.js supports loading obj+mtl file at the same time. 

Is there any way in react-vtk-js, especially **Reader** class  to load .obj and .mtl files at the same time?

This code works for me with .obj file. But I'm not sure how to parse url of .mtl file to Reader?

```
<div >
  <View>
    <GeometryRepresentation>
      <Reader
              vtkClass="vtkOBJReader"
              url={"https://kitware.github.io/vtk-js-datasets/data/obj-mtl/star-wars-vader-tie-fighter.obj"}
      />
    </GeometryRepresentation>
  </View>
</div>
```

**Comment by jourdain** [comment]
Not right now, but it would be easy to add.

**Comment by saodem74** [comment]
Thanks. It would be great to see that feature.

**Comment by jourdain** [comment]
Agree, I just need to find the time to get to it... ;-)

**Comment by jourdain** [comment]
Did you solve it on your side?

**Comment by saodem74** [comment]
No, I don't. 
I'm using your original code for the project since we have other important features needed to deploy.
