### ISSUE TITLE
Geometry/CutterExample not working

### ISSUE THREAD

**Issue by jadh4v** [Kitware/react-vtk-js#51]
When running the examples server. Switching to Geometry/CutterExample item in the dropdown list results in the following error: `Cannot GET /CutterExample.html`. We should either fix the example or remove this option from the item.

**Comment by osiux** [comment]
This is also fixed on #54 in case it makes it through :)

**Comment by osiux** [comment]
This should be fixed now!

**Comment by jadh4v** [comment]
@osiux Thanks for the fix.
