### ISSUE TITLE
Mouse picking returning incorrect worldspace position

### ISSUE THREAD

**Issue by tamaynard** [Kitware/react-vtk-js#93]
Seems like there's been a regression in the mouse picking feature since #37, as I am having a similar issue once again. Appears to be something with an incorrect z-value once again. Here's a simple repro case https://codesandbox.io/s/react-vtk-js-base-forked-o60cu0?file=/src/App.js. Clicking on the cube surface should place the red sphere on the surface of the cube under the mouse. However, it seems to be only intermittently selecting the correct coordinate.

**Comment by floryst** [comment]
The issue seems to have started with 1.8.5. I wonder if it's related to react-vtk-js still incorrectly bundling parts of vtk.js. Will have to examine this further.
